// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        kotlin_version = '2.2.0' // 这里写你要用的 Kotlin 版本
    }
    repositories {
        // 阿里云镜像加速（优先）
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }

        // 标准仓库
        google()
        mavenCentral()

        // 华为云镜像
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version" // Kotlin 插件

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        // 阿里云镜像加速（优先）
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }

        // rydeen
        maven { url "https://nexus.rydeen.com.cn/repository/platform-release" }

        // 标准仓库
        google()
        mavenCentral()

        // 华为云镜像
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
    }
}

// 全局统一排除重复文件
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            android {
                packagingOptions {
                    resources {
                        excludes += [
                            "META-INF/INDEX.LIST",
                            "META-INF/io.netty.versions.properties",
                            "META-INF/LICENSE",
                            "META-INF/LICENSE.txt",
                            "META-INF/NOTICE",
                            "META-INF/NOTICE.txt"
                        ]
                    }
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
